### ISSUE TITLE
error tu run NopFramework

### ISSUE THREAD

**Issue by agokrim** [alirezakhosravi/NopFramework#2]
Hi 
i receive this error when i run it 

An exception has been raised that is likely due to a transient failure. Consider enabling transient error resiliency by adding 'EnableRetryOnFailure()' to the 

thanks

**Comment by alirezakhosravi** [comment]
hi
in this adrress nop.web solution in App_Data folder, there is an appSetting.json file. if this is the first you want to run this solution, you need to delete this file and the  run again

**Comment by agokrim** [comment]
I have done it but i have the same error
System.InvalidOperationException: 'An exception has been raised that is likely due to a transient failure. Consider enabling transient error resiliency by adding 'EnableRetryOnFailure()' to the 'UseSqlServer' call.'

**Comment by alirezakhosravi** [comment]
I have tested on another machine, i did not find any problem.
Are you sure there is not any problem with your connection to sql server?

**Comment by agokrim** [comment]
to resolve the problem I have created  the database nopFramework  manualy 
but when i use update-database in pm console i receive  this error:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Nop.Core.Data.DataSettingsManager.LoadSettings(String filePath, Boolean reloadSettings, INopFileProvider fileProvider) in C:\Users\abdel\Desktop\MacDataMars2014\Projects\nopframwork\NopFramework\Libraries\Nop.Core\Data\DataSettingsManager.cs:line 38
   at Nop.Data.DesignTimeDbContextFactory.CreateDbContext(String[] args) in C:\Users\abdel\Desktop\MacDataMars2014\Projects\nopframwork\NopFramework\Libraries\Nop.Data\DesignTimeDbContextFactory.cs:line 16
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Object reference not set to an instance of an object.

**Comment by alirezakhosravi** [comment]
I've updated this solution and fixed some bugs.
Please get new version and try it.

**Comment by agokrim** [comment]
**When i compile i get those error :** 

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'IStoreContext' could not be found (are you missing a using directive or an assembly reference?)	Nop.Plugin.Widgets.NivoSlider	C:\Users\admin\Desktop\Projet\Brahim\nopcommerce\appSample\NopFramework\Plugins\Nop.Plugin.Widgets.NivoSlider\Components\WidgetsNivoSliderViewComponent.cs	15	Active
Error	CS0246	The type or namespace name 'IStoreContext' could not be found (are you missing a using directive or an assembly reference?)	Nop.Plugin.Widgets.NivoSlider	C:\Users\admin\Desktop\Projet\Brahim\nopcommerce\appSample\NopFramework\Plugins\Nop.Plugin.Widgets.NivoSlider\Components\WidgetsNivoSliderViewComponent.cs	20	Active
Error	CS0246	The type or namespace name 'IStoreContext' could not be found (are you missing a using directive or an assembly reference?)	Nop.Plugin.Widgets.NivoSlider	C:\Users\admin\Desktop\Projet\Brahim\nopcommerce\appSample\NopFramework\Plugins\Nop.Plugin.Widgets.NivoSlider\Controllers\WidgetsNivoSliderController.cs	18	Active
Error	CS0246	The type or namespace name 'IStoreContext' could not be found (are you missing a using directive or an assembly reference?)	Nop.Plugin.Widgets.NivoSlider	C:\Users\admin\Desktop\Projet\Brahim\nopcommerce\appSample\NopFramework\Plugins\Nop.Plugin.Widgets.NivoSlider\Controllers\WidgetsNivoSliderController.cs	24	Active
Error	CS0103	The name 'FacebookAuthenticationDefaults' does not exist in the current context	Nop.Plugin.ExternalAuth.Facebook	C:\Users\admin\Desktop\Projet\Brahim\nopcommerce\appSample\NopFramework\Plugins\Nop.Plugin.ExternalAuth.Facebook\Controllers\FacebookAuthenticationController.cs	97	Active
Error	CS0103	The name 'FacebookAuthenticationDefaults' does not exist in the current context	Nop.Plugin.ExternalAuth.Facebook	C:\Users\admin\Desktop\Projet\Brahim\nopcommerce\appSample\NopFramework\Plugins\Nop.Plugin.ExternalAuth.Facebook\Controllers\FacebookAuthenticationController.cs	122	Active
Error	CS0103	The name 'FacebookAuthenticationDefaults' does not exist in the current context	Nop.Plugin.ExternalAuth.Facebook	C:\Users\admin\Desktop\Projet\Brahim\nopcommerce\appSample\NopFramework\Plugins\Nop.Plugin.ExternalAuth.Facebook\Infrastructure\Cache\FacebookAuthenticationEventConsumer.cs	38	Active
Error	CS0103	The name 'FacebookAuthenticationDefaults' does not exist in the current context	Nop.Plugin.ExternalAuth.Facebook	C:\Users\admin\Desktop\Projet\Brahim\nopcommerce\appSample\NopFramework\Plugins\Nop.Plugin.ExternalAuth.Facebook\FacebookAuthenticationMethod.cs	51	Active
Error	CS1061	'ISettingService' does not contain a definition for 'SaveSettingOverridablePerStore' and no accessible extension method 'SaveSettingOverridablePerStore' accepting a first argument of type 'ISettingService' could be found (are you missing a using directive or an assembly reference?)	Nop.Plugin.Widgets.NivoSlider	C:\Users\admin\Desktop\Projet\Brahim\nopcommerce\appSample\NopFramework\Plugins\Nop.Plugin.Widgets.NivoSlider\Controllers\WidgetsNivoSliderController.cs	142	Active
--------------------------------
**when i use  update-database in pm
i get this:**
System.ArgumentNullException: Value cannot be null.
Parameter name: provider
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Nop.Core.Infrastructure.NopEngine.GetServiceProvider() in C:\Users\admin\Desktop\Projet\Brahim\nopcommerce\appSample\NopFramework\Libraries\Nop.Core\Infrastructure\NopEngine.cs:line 43
   at Nop.Core.Infrastructure.NopEngine.Resolve[T]() in C:\Users\admin\Desktop\Projet\Brahim\nopcommerce\appSample\NopFramework\Libraries\Nop.Core\Infrastructure\NopEngine.cs:line 238
   at Nop.Data.DesignTimeDbContextFactory.CreateDbContext(String[] args) in C:\Users\admin\Desktop\Projet\Brahim\nopcommerce\appSample\NopFramework\Libraries\Nop.Data\DesignTimeDbContextFactory.cs:line 26
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Value cannot be null.
Parameter name: provider

**Comment by alirezakhosravi** [comment]
I am currently working on Plugins and there are some major bugs in these projects. So please remove them from your source until I replace them with stable version. Tanks for your patience.
Remove plugins solution folder, and Remove all file in plugin folder from nop.web solution

**Comment by agokrim** [comment]
Is there any way to create the database  without using use update-database in pm console?
Thank you for your reply and your availability
